url: https://sofo1413.github.io
baseurl: /sofo1413.github.io/

# Site settings
title: sophie foster
email: sophie.foster@colorado.edu
description: "This is Sophie Foster's professional website!  She is a web developer and designer."


plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  

# Build settings
markdown: kramdown
permalink: pretty